services:
  nginx:
      container_name: nginx
      image: nginx:latest
      ports:
        - "8000:80"
      volumes:
        - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
        - ./public/:/var/www/html/public
      depends_on:
        - app 

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - APP_ENV=prod
      - APP_DEBUG=1
      - APP_SECRET=my_secret
    